### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by kylebot0** [Loquino/Frontend-Applications#1]
- Slim dat je eerst een mindmap hebt gemaakt, zo kan je makkelijk zien hoe je uiteindelijk bij je concept bent gekomen.

- Duidelijke research over de framework.
 
- Readme is nog niet up to date (mist nog).

- Logboek kan uitgebreider, vooral vertellen waarom je bepaalde dingen hebt gedaan.

**Comment by Loquino** [comment]
Dankjewel bro 🍐👍🏽 zal eraan werken!
